# Viagem
name: Viagens

# Controls when the action will run. 
on:
  push:
    branches: main


jobs: 
  autoviagem:
    # The type of runner that the job will run on
    runs-on: macOS-11

    # Load repo and install R
    steps:
    - uses: actions/checkout@v2
    - uses: r-lib/actions/setup-r@v2

    # Set-up R
    - name: Install packages
      run: |
        R -e 'install.packages("dplyr")'
        R -e 'install.packages("downloader")'
        R -e 'install.packages("lubridate")'
    # Run R script
    - name: Script Viagens
      run: Rscript viagens.R   
      
      
    - name: Commit results
      run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add IFS.rds
          git commit -F mensagem-comit.txt || echo "No changes to commit"
          git push origin || echo "No changes to commit"
        
      env:
        REPO_KEY: ${{secrets.GITHUB_TOKEN}}
        username: github-actions
