# Viagens
name: Viagens

# Controls when the action will run. 
on:
  push:
    branches: main


jobs: 
  autoviagem:
    # The type of runner that the job will run on
    runs-on: macOS-11

    # Load repo and install R
    steps:
    - uses: actions/checkout@v2
    - uses: r-lib/actions/setup-r@v2

    # Set-up R
    - name: Install packages
      run: |
        R -e 'install.packages("dplyr")'
        R -e 'install.packages("downloader")'
        R -e 'install.packages("lubridate")'
    # Run R script
    - name: Script Viagens
      run: Rscript viagens.R
      
# https://stackoverflow.com/questions/69198886/commit-only-when-file-exists
    - name: "Check file existence"
      id: check_files
      uses: andstor/file-existence-action@v1
      with:
        files: "IFS.rds"
      
    - name: Commit files
      if: steps.check_files.outputs.files_exists == 'true'
      run: |
         git config --local user.name actions-user
         git config --local user.email "actions@github.com"
         git add *
         git commit -am "GH ACTION Headlines $(date)"
         git push origin main -f
        
      env:
        REPO_KEY: ${{secrets.GITHUB_TOKEN}}
        username: github-actions
